name: Tests

on: [push, pull_request]

env:
  PYTHON_LATEST: "3.14"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install The Fuck with all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -Ur requirements.txt
          pip install -e .
      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: flake8
      - name: Run tests
        if: matrix.os != 'ubuntu-latest' || matrix.python-version != env.PYTHON_LATEST
        run: pytest -v --capture=sys tests
      - name: Run tests (including functional)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_LATEST
        run: |
          docker build -t thefuck/python3 -f tests/Dockerfile --build-arg PYTHON_VERSION=3 .
          pytest -v --capture=sys tests --enable-functional
